In [3]:
import csv
%precision 2

with open("mpg.csv") as csvFile:
    mpg = list(csv.DictReader(csvFile))

mpg[:3]


FileNotFoundError: [Errno 2] No such file or directory: 'mpg.csv'

In [2]:
len(mpg)

'%.2f'

In [4]:
mpg[0].keys()

NameError: name 'mpg' is not defined

This is how to find the average cty fuel economy across all cars. All values in the dictionaries are strings, so we need to convert to float.

In [6]:
sum(float(d['cty']) for d in mpg) / len(mpg)

NameError: name 'mpg' is not defined

<br>
Similarly this is how to find the average hwy fuel economy across all cars.

In [7]:
sum(float(d['hwy']) for d in mpg) / len(mpg)

NameError: name 'mpg' is not defined

Use set to return the unique values for the number of cylinders the cars in our dataset have.

In [8]:
cylinders = set(d['cyl'] for d in mpg)
cylinders

NameError: name 'mpg' is not defined

<br>
Here's a more complex example where we are grouping the cars by number of cylinder, and finding the average cty mpg for each group.

In [9]:
CtyMpgByCyl = []

for c in cylinders: # iterate over all the cylinder levels
    summpg = 0
    cyltypecount = 0
    for d in mpg: # iterate over all dictionaries
        if d['cyl'] == c: # if the cylinder level type matches,
            summpg += float(d['cty']) # add the cty mpg
            cyltypecount += 1 # increment the count
    CtyMpgByCyl.append((c, summpg / cyltypecount)) # append the tuple ('cylinder', 'avg mpg')

CtyMpgByCyl.sort(key=lambda x: x[0])
CtyMpgByCyl

NameError: name 'cylinders' is not defined

<br>
And here's an example of how to find the average hwy mpg for each class of vehicle in our dataset.

In [10]:
HwyMpgByClass = []

for t in vehicleclass: # iterate over all the vehicle classes
    summpg = 0
    vclasscount = 0
    for d in mpg: # iterate over all dictionaries
        if d['class'] == t: # if the cylinder amount type matches,
            summpg += float(d['hwy']) # add the hwy mpg
            vclasscount += 1 # increment the count
    HwyMpgByClass.append((t, summpg / vclasscount)) # append the tuple ('class', 'avg mpg')

HwyMpgByClass.sort(key=lambda x: x[1])
HwyMpgByClass

NameError: name 'vehicleclass' is not defined

# Date and Time

In [11]:
import datetime as dt
import time as tm

In [12]:
tm.time()

1497768929.16

In [14]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2017, 6, 18, 12, 26, 22, 861382)

In [16]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute

(2017, 6, 18, 12, 26)

In [17]:
timedelta = dt.timedelta(days=100)

In [19]:
today = dt.date.today()

In [20]:
today - timedelta

datetime.date(2017, 3, 10)

# The Python Programming Language :- Object and Map()

In [21]:
class Person:
    department = "Computer Science"
    
    def set_name(self,attr_name):
        self.name = attr_name
    
    def set_location(self,attr_location):
        self.location = attr_location
    

In [22]:
store1 = [10.00,11.00,12.34,2.34]
store2 = [9.00,11.00,12.34,2.01]
cheapest = map(min,store1,store2)
cheapest

# Lambdas and List Comprehension

In [23]:
my_function = lambda a,b,c: a+b+c
my_function(1,2,3)

6

In [24]:
list = [number for number in range(0,10000) if number %2 ==0]

In [25]:
list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

# Numpy

In [26]:
import numpy as np

In [28]:
myList = [1,2,3]
x = np.array(myList)
x

array([1, 2, 3])

In [30]:
y = np.array([5,7,11])
y

array([ 5,  7, 11])

In [33]:
y = np.array([[5,7,11],[2,3,4]])
y

array([[ 5,  7, 11],
       [ 2,  3,  4]])

In [34]:
np.shape(y)

(2, 3)

In [35]:
a = np.arange(0,30,2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [37]:
m = a.reshape([3,5])
m

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [39]:
o = np.linspace(0,4,9)
o

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [42]:
np.ones((2,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [43]:
np.zeros((3,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [44]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [45]:
np.array([1,2,3]*2)

array([1, 2, 3, 1, 2, 3])

In [46]:
np.repeat([1,2,3],2)

array([1, 1, 2, 2, 3, 3])

In [47]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [48]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [49]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [51]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [52]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[ 4 10 18]
[ 0.25  0.4   0.5 ]


In [53]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

32

In [55]:
z = np.array([y, y**2])
print(len(z)) # number of rows of array
z

2


array([[ 4,  5,  6],
       [16, 25, 36]])

In [56]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [57]:
z.shape

(2, 3)

In [58]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [59]:
z.T.shape

(3, 2)

In [60]:
z.dtype

dtype('int64')

In [61]:
z = z.astype('f')
z.dtype

dtype('float32')

Math Functions

In [62]:
a = np.array([-4, -2, 1, 3, 5])

In [63]:
a.sum()

3

In [64]:
a.max()

5

In [65]:
a.min()

-4

In [66]:
a.mean()

0.60

In [67]:
a.std()

3.26

In [68]:
a.argmax()

4

In [69]:
a.argmin()

0

In [70]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [71]:
s[0], s[4], s[-1]

(0, 16, 144)

In [72]:
s[1:5]

array([ 1,  4,  9, 16])

In [73]:
s[-4:]

array([ 81, 100, 121, 144])

In [74]:
s[-5::-2]

array([64, 36, 16,  4,  0])

In [75]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [76]:
r[2, 2]

14

In [77]:
r[3, 3:6]

array([21, 22, 23])

In [78]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [79]:
r[r > 30]

array([31, 32, 33, 34, 35])

In [80]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

# Copying Data
Be careful with copying and modifying arrays in NumPy!

In [81]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [82]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [83]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [84]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [85]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


## Iterating Over Arrays
Let's create a new 4 by 3 array of random numbers 0-9.

In [86]:
test = np.random.randint(0, 10, (4,3))
test

array([[0, 3, 9],
       [1, 3, 8],
       [5, 1, 5],
       [7, 7, 3]])

In [87]:
for row in test:
    print(row)

[0 3 9]
[1 3 8]
[5 1 5]
[7 7 3]


In [88]:
for i in range(len(test)):
    print(test[i])

[0 3 9]
[1 3 8]
[5 1 5]
[7 7 3]


In [89]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [0 3 9]
row 1 is [1 3 8]
row 2 is [5 1 5]
row 3 is [7 7 3]


In [90]:
test2 = test**2
test2

array([[ 0,  9, 81],
       [ 1,  9, 64],
       [25,  1, 25],
       [49, 49,  9]])

In [91]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[0 3 9] + [ 0  9 81] = [ 0 12 90]
[1 3 8] + [ 1  9 64] = [ 2 12 72]
[5 1 5] + [25  1 25] = [30  2 30]
[7 7 3] + [49 49  9] = [56 56 12]


In [92]:
['a','b']+[1,2]

['a', 'b', 1, 2]

In [93]:
lambda x: x+2

<function __main__.<lambda>>